# Generated by Django 3.2.6 on 2022-03-07 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adhyay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shlok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('shlok', models.TextField()),
                ('meaning', models.TextField()),
                ('adhyay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shlok.adhyay')),
            ],
        ),
    ]
