# Generated by Django 3.2.6 on 2022-03-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shlok', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhyay',
            name='subtitle',
            field=models.CharField(default='mahesh', max_length=150),
            preserve_default=False,
        ),
    ]
